version: '3.1'

services:

  ode-postgres:
    build: ..
    ports:
      - "5432:5432"
    restart: always
    container_name: ode-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ode

